server:
  port: 4047

eureka:
  client:
    service-url:
      defaultZone: http://localhost:4037/eureka
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lennuo/boot-jpa
          search-paths: config
          #username: username  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
          #password: password

