server:
  port: 4043

eureka:
  instance:
    hostname: city-api
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:4037/eureka
    fetch-registry: false
    register-with-eureka: true

spring:
  application:
    name: city-api